### ISSUE TITLE
Deprecated selector in `scroll-searcher/styles/scroll-searcher.less`

### ISSUE THREAD

**Issue by iml885203** [Aakash1312/scroll-searcher#15]
In `scroll-searcher/styles/scroll-searcher.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor .scroll-searcher,
atom-text-editor::shadow .scroll-searcher` => `atom-text-editor .scroll-searcher,
atom-text-editor.editor .scroll-searcher`

* `atom-text-editor .scroll-marker,
atom-text-editor::shadow .scroll-marker` => `atom-text-editor .scroll-marker,
atom-text-editor.editor .scroll-marker`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by Aakash1312** [comment]
Scroll searcher has been updated. Due to recent shadow dom update, this new version will only work with Atom >= v1.13.0.
https://atom.io/packages/scroll-searcher
