### ISSUE TITLE
Disable highlight when search panel is hidden

### ISSUE THREAD

**Issue by Sigmanor** [Aakash1312/scroll-searcher#4]
Hi. It would be nice add the settings that disable highlight on the scrollbar when the search panel is hidden.

**Comment by Aakash1312** [comment]
yeah I'll look for that. Thanks for the feedback. :smile:

**Comment by Aakash1312** [comment]
Scroll-searcher package has been updated. [Scroll-Searcher-v4.0]( https://atom.io/packages/scroll-searcher)
Feel free to give feedback. :)

**Comment by Sigmanor** [comment]
Thank you! All working fine.
