### ISSUE TITLE
Markers appear at incorrect positions when Soft Wrap is turned on.

### ISSUE THREAD

**Issue by willemodendaal** [Aakash1312/scroll-searcher#5]

**Comment by Aakash1312** [comment]
Yeah I checked it. I'll be working on that. Thanks for your feedback! :smile:

**Comment by willemodendaal** [comment]
Great package :)   Wish I had time to help out!

**Comment by Aakash1312** [comment]
I have updated the package. Feel free to give feedback.

**Comment by willemodendaal** [comment]
Excellent, thanks!
