### ISSUE TITLE
doesn't appear nothing

### ISSUE THREAD

**Issue by pedrosmmc** [Aakash1312/scroll-searcher#6]
doesn't appear nothing on the right side after do a find!!!
doesn't make anything with the settings... just raw install and toogled.

**Comment by Aakash1312** [comment]
Can you please describe your problem ? Like information about your operating system and your atom version and steps to reproduce the problem.

**Comment by gmaggio** [comment]
Same for me. After installing the package, I don't see any **markers** on the sidebar after **find-and-replace**.

I'm using Windows 10 with Atom 1.10.

**Comment by gmaggio** [comment]
Hmmm... Not sure what's happened but now the markers suddenly appears...

**Comment by techv76** [comment]
I'm having the same issue as above. The markers are not showing up in the sidebar at all. I've also tried re-install and closing & re-loading Atom. 

OSX 10.11.5  Atom 1.10

**Comment by gmaggio** [comment]
Hmmm.. now it's not showing again. It seems to randomly works. Not sure what triggers it.

**Comment by Aakash1312** [comment]
I am not sure what the problem is. After installing package, you need to to toggle it using short-cut `ctrl+alt+a` or using `Packages > Scroll Searcher > Toggle`
If you guys face the problem anyway, then please let me know.

**Comment by gmaggio** [comment]
Oh.. ok... Yes, it works... I must've forgotten to toggle it on after restart. Would it be possible to make it **enabled (turned on) by default**?

**Comment by Aakash1312** [comment]
Presently there is no such feature in the package. But I would consider your point in the next release.

**Comment by Aakash1312** [comment]
@gmaggio thanks for your feedback :)

**Comment by Aakash1312** [comment]
@cannaV and @pedrosmmc  if you have no problems, then I'm closing this issue.
You can reopen it if you face difficulties.
